### ISSUE TITLE
принято

### ISSUE THREAD

**Issue by Parapitek** [sinooox/cycles#1]
использовали списки и строки, когда можно было обойтись и без них, но это ладно. меня больше смущает код вида:
<pre>
for i in range(n+1):
        if i == 0:
            continue
</pre>

что мешает начинать не с нуля, а с единицы?

**Comment by sinooox** [comment]
чтобы не умножать на ноль

**Comment by Parapitek** [comment]
ничего страшного. первую задачу я решил бы так
<pre>
N = int(input('Введите N: '))

for i in range(1, N):
  if i**2 > N:
    break
  print(i**2, end=' ')
</pre>
